name: flappy_jet_pro
description: "FlappyJet Pro - Modern Endless Runner with Progressive Themes"
publish_to: 'none'
version: 1.4.3+13

environment:
  sdk: ^3.8.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Game Engine
  flame: ^1.32.0
  
  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.0
  
  # Storage & Preferences
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio - Modern Flame Audio Stack
  flame_audio: ^2.1.0
  
  # Ads & Monetization
  google_mobile_ads: ^5.3.1
  
  # Firebase Analytics & Services
  firebase_analytics: ^11.3.3
  firebase_remote_config: ^5.1.3
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.10
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_performance: ^0.10.0+8
  google_sign_in: ^6.2.2
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  
  # UI & Animations
  flutter_animate: ^4.5.2
  confetti: ^0.7.0
  
  # Content Moderation
  safe_text: ^1.0.8
  
  # Device & System
  vibration: ^3.1.3  # Updated to latest version for NDK 27 compatibility
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Performance & Development
  path_provider: ^2.1.0
  in_app_purchase: ^3.2.1
  
  # App Store Integration
  in_app_review: ^2.0.9
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Social Sharing
  share_plus: ^7.2.2
  screenshot: ^3.0.0
  url_launcher: ^6.2.5
  

  provider: any
  lottie: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  integration_test:
    sdk: flutter
  test: ^1.25.15
  # Enhanced testing framework for leaderboard TDD
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  # WebSocket and HTTP testing
  web_socket_channel: ^3.0.3
  # Local storage testing
  sqflite_common_ffi: ^2.3.3
  # Flame testing utilities
  flame_test: ^1.0.0

# App Icon Configuration (Removed duplicate - using flutter_launcher_icons below)

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/images/effects/
    - assets/images/jets/
    # - assets/images/jets/states/     # 🔥 BLOCKBUSTER jet fire sprites (directory not found)
    - assets/images/homepage/      # Stunning homepage assets
    - assets/images/buttons/       # Button graphics  
    - assets/images/icons/         # Homepage button icons
    # - assets/images/ui/ # Removed - using pure Flutter UI instead            # Daily streak and UI assets
    - assets/images/icons/missions/   # Mission 3D icons
    - assets/images/backgrounds/   # Background elements
    - assets/images/text/          # Custom text assets
    - assets/audio/
    - assets/audio/android_optimized/
    - assets/backgrounds/
    - assets/images/obstacles/   # Dynamic obstacle sprites
    - assets/particles/
    
  # fonts:
  #   - family: GameFont
  #     fonts:
  #       - asset: assets/fonts/PressStart2P-Regular.ttf

# Flutter Launcher Icons Configuration - PROPER ADAPTIVE ICON
flutter_launcher_icons:
  android: true
  ios: true
  
  # Main icon for iOS and legacy Android (pre-API 26)
  image_path: "assets/images/app_icon/logo.png"
  min_sdk_android: 21
  
  # CRITICAL: Proper Android Adaptive Icon (API 26+)
  # The key is to NOT use the same image for foreground and background
  
  # Background: Simple solid color that complements the logo
  adaptive_icon_background: "#4FC3F7"
  
  # Foreground: The logo will be automatically centered and scaled
  # flutter_launcher_icons will handle the safe zone automatically
  adaptive_icon_foreground: "assets/images/app_icon/logo.png"
  
  # Advanced options for better results
  remove_alpha_ios: true
  
  # Platform-specific settings
  platforms:
    android:
      adaptive_icon_background: "#4FC3F7"
      adaptive_icon_foreground: "assets/images/app_icon/logo.png"
    ios:
      generate: true
      image_path: "assets/images/app_icon/logo.png" 