// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '${defaultTargetPlatform.name} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6Cbv1mTWilDIXDsMuXDB7PA-8rbLpIs',
    appId: '1:861286493216:android:6fa25aec2fa3528be92045',
    messagingSenderId: '861286493216',
    projectId: 'flappyjet-b31f9',
    storageBucket: 'flappyjet-b31f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygq88sH-2E1-zrTz9beKYVeRjf18dXVQ',
    appId: '1:861286493216:ios:b2ea7b7e3a893178e92045',
    messagingSenderId: '861286493216',
    projectId: 'flappyjet-b31f9',
    storageBucket: 'flappyjet-b31f9.firebasestorage.app',
    iosBundleId: 'com.flappyjet.pro.flappyJetPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygq88sH-2E1-zrTz9beKYVeRjf18dXVQ',
    appId: '1:861286493216:ios:b2ea7b7e3a893178e92045',
    messagingSenderId: '861286493216',
    projectId: 'flappyjet-b31f9',
    storageBucket: 'flappyjet-b31f9.firebasestorage.app',
    iosClientId: '861286493216-your-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.flappyjet.pro.flappyJetPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-6Cbv1mTWilDIXDsMuXDB7PA-8rbLpIs',
    appId: '1:861286493216:web:your-web-app-id',
    messagingSenderId: '861286493216',
    projectId: 'flappyjet-b31f9',
    authDomain: 'flappyjet-b31f9.firebaseapp.com',
    storageBucket: 'flappyjet-b31f9.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB-6Cbv1mTWilDIXDsMuXDB7PA-8rbLpIs',
    appId: '1:861286493216:web:your-web-app-id',
    messagingSenderId: '861286493216',
    projectId: 'flappyjet-b31f9',
    authDomain: 'flappyjet-b31f9.firebaseapp.com',
    storageBucket: 'flappyjet-b31f9.firebasestorage.app',
  );
}
